//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import javax.swing.*;

public class AgentGUI extends JPanel {
    public JButton broadTransaction;
    public JButton broadcastCurrentBlock;
    public JButton addTransaction;
    public JButton hashBlock;
    public JButton mineBlock;
    private JToggleButton jcomp6;
    private JLabel jcomp7;
    private JTextArea logArea;
    public JList currentTransactions;
    private JLabel jcomp10;
    private JLabel jcomp11;
    public JTextArea powArea;
    private JTextField blockChainInfo;
    private JLabel jcomp14;
    private JLabel agentName;
    public DefaultListModel currentTrans = new DefaultListModel();

    public AgentGUI() {
        //construct preComponents
        String[] jcomp9Items = {"Transaction 1", "Transaction 2", "Transaction 3"};

        //construct components
        broadTransaction = new JButton("Diffuser transaction");
        broadcastCurrentBlock = new JButton("Diffuser le bloc courant");
        addTransaction = new JButton("Créer une transaction");
        hashBlock = new JButton("Hasher bloc");
        mineBlock = new JButton("Miner bloc");
        jcomp6 = new JToggleButton("Miner Mode", false);
        jcomp7 = new JLabel("Informations sur la Blockchain");
        logArea = new JTextArea(5, 5);
        currentTransactions = new JList(currentTrans);
        jcomp10 = new JLabel("Logs");
        jcomp11 = new JLabel("Preuve de travail");
        powArea = new JTextArea(5, 5);

        powArea.setText("Target: 1 \n Nonce: 1");

        blockChainInfo = new JTextField(5);
        jcomp14 = new JLabel("Bloc en cours");
        agentName = new JLabel("AgentName");

        //adjust size and set layout
        setPreferredSize(new Dimension(837, 1400));
        setLayout(null);

        //add components
        add(broadTransaction);
        add(broadcastCurrentBlock);
        add(addTransaction);
        add(hashBlock);
        add(mineBlock);
        add(jcomp6);
        add(jcomp7);
        add(logArea);
        add(currentTransactions);
        add(jcomp10);
        add(jcomp11);
        add(powArea);
        add(blockChainInfo);
        add(jcomp14);
        add(agentName);

        //set component bounds (only needed by Absolute Positioning)
        addTransaction.setBounds(30, 115, 150, 55);
        broadcastCurrentBlock.setBounds(30, 185, 150, 55);
        broadTransaction.setBounds(30, 255, 150, 55);
        hashBlock.setBounds(30, 325, 150, 55);
        mineBlock.setBounds(30, 395, 150, 55);
        jcomp6.setBounds(55, 470, 100, 25);
        jcomp7.setBounds(425, 15, 185, 35);
        logArea.setBounds(520, 255, 285, 900);
        currentTransactions.setBounds(200, 145, 290, 1010);
        jcomp10.setBounds(650, 230, 100, 25);
        jcomp11.setBounds(610, 110, 100, 25);
        powArea.setBounds(520, 135, 280, 90);
        blockChainInfo.setBounds(195, 50, 605, 40);
        jcomp14.setBounds(300, 120, 100, 25);
        agentName.setBounds(30, 50, 100, 25);
    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("MyPanel");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new AgentGUI());
        frame.pack();
        frame.setVisible(true);
    }

    public void setAgentName(String agentName) {
        this.agentName.setText(agentName);
    }

    public void logStuff(String logg) {
        this.logArea.setText(this.logArea.getText() + "\n" + logg);
    }

    public void setBlockChainInfo(String blockChainInfo) {
        this.blockChainInfo.setText(blockChainInfo);
    }
}
